[package]
name = "webgraph-clib-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cbindgen = "0.29.2"
libc = "0.2.177"
webgraph = { git = "https://github.com/vigna/webgraph-rs.git", version = "0.5.0" }

[lib]
name = "webgraphclibrs"
crate-type = ["staticlib"]
